# JavaScript错误处理 #
## JavaScript错误-throw、try和catch ##
try语句测试代码块的错误。

catch语句处理错误。

throw语句创建自定义错误。
## JavaScript错误 ##
当JavaScript引擎执行JavaScript代码时，会发生各种错误:

可能是语法错误，通常是程序员造成的编码错误或错别字。

可能是拼写错误或语言中缺少的功能（可能由于浏览器差异）。

可能是由于来自服务器或用户的错误输出而导致的错误。

当然，也可能是由于许多其他不可预知的因素。
## JavaScript抛出(throw)错误 ##
当错误发生时，当事情出问题是，JavaScript引擎通常会停止，并生成一个错误信息。

描述这种情况的技术术语是：JavaScript将抛出一个错误。
## JavaScript try和catch ##
try语句允许我们定义在执行时进行错误测试的代码块。

catch语句允许我们定义当try代码块发生错误时，所执行的代码块。

JavaScript语句try和catch是成对出现的。

语法：
	
	try{
	//在这里运行代码
	}
	catch（err）{
	//在这里处理错误
	}
在下面的例子中，我们故意在try块的代码中写一个错字。

catch块会捕捉到try块中的错误，并执行代码来处理它

	<script>
	var txt="";
	function message()
	{
	try
  	{
 	 adddlert("Welcome guest!");
  	}
	catch(err)
  	{
  	txt="本页有一个错误。\n\n";
  	txt+="错误描述：" + err.message + "\n\n";
  	txt+="点击确定继续。\n\n";
 	 alert(txt);
 	 }
	}
	</script>
	<input type="button" value="查看消息" onclick="message()" />
## Throw语句 ##
throw语句允许我们创建自定义错误。

正确的技术术语是:创建或抛出异常(exception)。

如果把throw与try和catch一起使用，那么您能够控制程序流，并生成自定义的错误消息。

语法：

	throw exception
异常可以是JavaScript字符串、数字、逻辑值或对象。

	function myFunction(){
	try{ 
		var x=document.getElementById("demo").value;
		if(x=="")    throw "值为空";
		if(isNaN(x)) throw "不是数字";
		if(x>10)     throw "太大";
		if(x<5)      throw "太小";
	}
	catch(err){
		var y=document.getElementById("mess");
		y.innerHTML="错误：" + err + "。";
	}
	}
	</script>

	<p>请输出一个 5 到 10 之间的数字:</p>
	<input id="demo" type="text">
	<button type="button" onclick="myFunction()">测试输入</button>
	<p id="mess"></p>

